version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    restart: unless-stopped


  frontend:
    build:
      context: ./weather-app
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    
